version: "3.8"

services:
  service_1:
    build: ./service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8001/hello"]
      interval: 30s
      timeout: 10s
      retries: 3

  service_2:
    build: ./service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy
